### ISSUE TITLE
Linter/Formatter入れたい

### ISSUE THREAD

**Issue by fummicc1** [fummicc1/flutter-instagram-clone#96]
環境でもフォーマットスタイルが違うしVSCodeとAndroid Studioでも修正してないところが差分に出ちゃう

**Comment by organic-nailer** [comment]
わかる

**Comment by fummicc1** [comment]
Linterは公式のパッケージがあるみたい👀→https://github.com/flutter/packages/tree/master/packages/flutter_lints

formatに関しては公式のパッケージとかはないけど、`flutter format path`でpathにあるファイルをフォーマットしてくれるみたい→https://flutter.dev/docs/development/tools/formatting

flutterでビルドするたびにformatできれば良いけどそういう仕組みがあるか調べようと思う

**Comment by organic-nailer** [comment]
push前にLinterかけてpassしないとpushできないようにするとかもやりたい
https://qiita.com/Syuparn/items/9e107e0aaf1a61b260b5 このへんかな
